SELECT
  TEX.ARTICULO_ID,
  TEX.ARTICULO,
  TEX.NOMBRE_ARTICULO,
  TEX.EXISTENCIA,
  (SELECT PA.PRECIO 
   FROM PRECIOS_EMPRESA PE 
     INNER JOIN PRECIOS_ARTICULOS PA ON (PE.PRECIO_EMPRESA_ID = PA.PRECIO_EMPRESA_ID) 
   WHERE PE.PRECIO_EMPRESA_ID = 260 AND PA.ARTICULO_ID=TEX.ARTICULO_ID) AS FILIAL,
  (SELECT PA.PRECIO
   FROM PRECIOS_EMPRESA PE 
     INNER JOIN PRECIOS_ARTICULOS PA ON (PE.PRECIO_EMPRESA_ID = PA.PRECIO_EMPRESA_ID) 
   WHERE PE.PRECIO_EMPRESA_ID = 259 AND PA.ARTICULO_ID=TEX.ARTICULO_ID) AS MAYOREO,
  (SELECT PA.PRECIO 
   FROM PRECIOS_EMPRESA PE 
     INNER JOIN PRECIOS_ARTICULOS PA ON (PE.PRECIO_EMPRESA_ID = PA.PRECIO_EMPRESA_ID) 
   WHERE PE.PRECIO_EMPRESA_ID = 42 AND PA.ARTICULO_ID=TEX.ARTICULO_ID) AS LISTA
FROM
(
  SELECT 
    ARTICULO_ID,
    ARTICULO,
	NOMBRE_ARTICULO,
    LINEA_ARTICULO_ID,
    (ENTRADAS - SALIDAS) AS EXISTENCIA
  FROM 
  (
	SELECT 
	  A.ARTICULO_ID,
	  (CLAVES_ARTICULOS.CLAVE_ARTICULO || ' - ' || A.NOMBRE) AS ARTICULO,
	  A.NOMBRE AS NOMBRE_ARTICULO,
	  A.LINEA_ARTICULO_ID,
	  (SELECT SUM(DIDE.UNIDADES) AS FIELD_1 FROM DOCTOS_IN_DET DIDE WHERE CANCELADO LIKE 'N' AND DIDE.APLICADO LIKE 'S' AND DIDE.TIPO_MOVTO LIKE 'E' AND DIDE.ALMACEN_ID = |ALMACEN_ID| AND DIDE.ARTICULO_ID = A.ARTICULO_ID) AS ENTRADAS,
	  (SELECT SUM(DIDS.UNIDADES) AS FIELD_1 FROM DOCTOS_IN_DET DIDS WHERE DIDS.CANCELADO LIKE 'N' AND DIDS.APLICADO LIKE 'S' AND DIDS.TIPO_MOVTO LIKE 'S' AND DIDS.ALMACEN_ID = |ALMACEN_ID| AND DIDS.ARTICULO_ID = A.ARTICULO_ID) AS SALIDAS
	FROM
	  CLAVES_ARTICULOS
	  INNER JOIN ARTICULOS A ON (CLAVES_ARTICULOS.ARTICULO_ID = A.ARTICULO_ID)
	  INNER JOIN ROLES_CLAVES_ARTICULOS ON (CLAVES_ARTICULOS.ROL_CLAVE_ART_ID = ROLES_CLAVES_ARTICULOS.ROL_CLAVE_ART_ID)
	WHERE
	  ROLES_CLAVES_ARTICULOS.ES_PPAL LIKE 'S'
  )
) TEX
INNER JOIN LINEAS_ARTICULOS LA ON LA.LINEA_ARTICULO_ID = TEX.LINEA_ARTICULO_ID
INNER JOIN GRUPOS_LINEAS GL ON GL.GRUPO_LINEA_ID = LA.GRUPO_LINEA_ID
WHERE
  EXISTENCIA IS NOT NULL 
  AND EXISTENCIA > 0
  AND GL.GRUPO_LINEA_ID IN (|GRUPOS|)
ORDER BY
  NOMBRE_ARTICULO