SELECT
  TEX.ARTICULO_ID,
  TEX.ARTICULO,
  TEX.EXISTENCIA,
  (SELECT PA.PRECIO 
   FROM PRECIOS_EMPRESA PE 
     INNER JOIN PRECIOS_ARTICULOS PA ON (PE.PRECIO_EMPRESA_ID = PA.PRECIO_EMPRESA_ID) 
   WHERE PE.PRECIO_EMPRESA_ID = 260 AND PA.ARTICULO_ID=TEX.ARTICULO_ID) AS FILIAL,
  (SELECT PA.PRECIO
   FROM PRECIOS_EMPRESA PE 
     INNER JOIN PRECIOS_ARTICULOS PA ON (PE.PRECIO_EMPRESA_ID = PA.PRECIO_EMPRESA_ID) 
   WHERE PE.PRECIO_EMPRESA_ID = 259 AND PA.ARTICULO_ID=TEX.ARTICULO_ID) AS MAYOREO,
  (SELECT PA.PRECIO 
   FROM PRECIOS_EMPRESA PE 
     INNER JOIN PRECIOS_ARTICULOS PA ON (PE.PRECIO_EMPRESA_ID = PA.PRECIO_EMPRESA_ID) 
   WHERE PE.PRECIO_EMPRESA_ID = 42 AND PA.ARTICULO_ID=TEX.ARTICULO_ID) AS LISTA
FROM
(
  SELECT 
    ARTICULO_ID,
    ARTICULO,
    LINEA_ARTICULO_ID,
    (ENTRADAS - SALIDAS) AS EXISTENCIA
  FROM 
  (
    SELECT
      A.ARTICULO_ID,
      A.NOMBRE AS ARTICULO,
      A.LINEA_ARTICULO_ID,
      (SELECT SUM(DIDE.UNIDADES) FROM DOCTOS_IN_DET DIDE WHERE CANCELADO LIKE 'N' AND DIDE.APLICADO LIKE 'S' AND DIDE.TIPO_MOVTO LIKE 'E' AND DIDE.ALMACEN_ID = |ALMACEN_ID| AND DIDE.ARTICULO_ID = A.ARTICULO_ID) AS ENTRADAS,
      (SELECT SUM(DIDS.UNIDADES) FROM DOCTOS_IN_DET DIDS WHERE DIDS.CANCELADO LIKE 'N' AND DIDS.APLICADO LIKE 'S' AND DIDS.TIPO_MOVTO LIKE 'S' AND DIDS.ALMACEN_ID = |ALMACEN_ID| AND DIDS.ARTICULO_ID = A.ARTICULO_ID) AS SALIDAS
    FROM
      ARTICULOS A
  )
) TEX
INNER JOIN LINEAS_ARTICULOS LA ON LA.LINEA_ARTICULO_ID = TEX.LINEA_ARTICULO_ID
INNER JOIN GRUPOS_LINEAS GL ON GL.GRUPO_LINEA_ID = LA.GRUPO_LINEA_ID
WHERE
  EXISTENCIA IS NOT NULL 
  AND EXISTENCIA > 0
  AND GL.GRUPO_LINEA_ID IN (|GRUPOS|)
ORDER BY
  ARTICULO